### ISSUE TITLE
"unexpected keyword argument" in ConvertXML.py

### ISSUE THREAD

**Issue by AllesEins** [jbjorne/TEES#16]
I stumbled over this: the arguments to "STTools.loadSet()" In line 566 & 572 of "Utils/STFormat/ConvertXML.py" are wrong; namely "a2Tag" has to be "a2Tags".

Best, Franz

**Comment by jbjorne** [comment]
Dear Franz,

The argument should be correct now. I also added to ConvertXML.py a new command line parameter 'inputTags' that can be used to define the a2-file extensions for 'STTools.loadSet()'. Hope this works!

Best Regards,
Jari

**Comment by AllesEins** [comment]
Dear Jari,
That was swift and the additional parameter is helpful, thanks!
Another issue I stumbled upon: the same arguments mentioned above have as default a 'string' value, but STTools.load() assumes a list value only ("for a2Tag in asTags" -- line 60). For my local code I inserted a differentiation to deal with string values as well.

All the best,
Franz

**Comment by jbjorne** [comment]
I'm sorry, which arguments have the default value as a string? At least 'STTools.loadSet()' has a list (["a2", "rel"]) as the default a2Tags-value, and so does 'Document.load()'?

**Comment by AllesEins** [comment]
Oh sorry, it was again in line 566 & 572 of the former "Utils/STFormat/ConvertXML.py". (I didn't use your updated version)
With the additional line "options.inputTags = options.inputTags.split(",")" (line 559) it should work now as intended. Thanks again.
