### ISSUE TITLE
Does -c PBS option in train.py actually work?

### ISSUE THREAD

**Issue by ngiordani** [jbjorne/TEES#18]
I tried to use this option with value PBS, as documented [here](https://github.com/jbjorne/TEES/wiki/Training), but I got an error:

New local connection connection=PBS:debug=False
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    connection=options.connection, subset=options.subset, folds=options.folds)
  File "train.py", line 86, in train
    connection = getConnection(connection)
  File "/juicier/scr107/scr/natalias/TEES/TEES/Utils/Connection/Connection.py", line 31, in getConnection
    exec "ConnectionClass = " + connection["connection"] + "Connection"
  File "<string>", line 1, in <module>
NameError: name 'PBSConnection' is not defined

Looking at the code in Util.Connections.Connection, it doesn't seem like this value receives any special handling. I'm wondering if this can be expected to work and whether there is an easy fix that will get in working.

**Comment by jbjorne** [comment]
Unfortunately, the cluster where I used PBS has been replaced with a newer one using SLURM, so I cannot test the PBS code anymore. However, it might be possible that the old PBS code still works, or at least it would be possible to get it working again.

To test the connection, first you need to add the "from PBSConnection import PBSConnection" line to Utils.Connection.Connection. Then, you may need to update the PBSConnection class to work with your PBS environment. Running the connection with "debug=True" may be helpful if it doesn't work. I think it was working when I last used it, but that was several years ago, and I have no idea how similar PBS environments on different clusters are.
