### ISSUE TITLE
About how to generate the fancy annotated picture

### ISSUE THREAD

**Issue by chengkun-wu** [jbjorne/TEES#22]
Hi @jbjorne, 

Which tool did you use to generate the following diagram? Thanks！

![image](https://cloud.githubusercontent.com/assets/1331567/23739951/3a508d14-04dc-11e7-8c77-4a10af1ebf5e.png)

**Comment by jbjorne** [comment]
Hi  @chengkun-wu,

The graph image was generated with an old HTML/SVG visualizer which was included in TEES 1.0 (http://bionlp.utu.fi/eventextractionsoftware.html). However, most of the images used in TEES papers (like the one you mentioned) have been extensively edited in Inkscape, with just the basic graph structure coming from the visualizer.

The old HTML visualizer is not compatible with the later versions, but I now added the core part of the graph drawing system to the TEES development branch, you can find it at https://github.com/jbjorne/TEES/blob/development/Utils/Visualization/GraphToSVG.py. You can run it for example like this:

`python GraphToSVG.py -i GE11-devel.xml -d GE11.d0.s6 -o image.svg`

A more comprehensive option for visualizing annotations would be BRAT (http://brat.nlplab.org/index.html). Their online demo may have some kind of sandbox environment where you can input your own text and annotations, which might be used to easily generate visualizations.

**Comment by chengkun-wu** [comment]
Many thanks for the reply! That's cool!
